# Generated by Django 4.1.1 on 2022-09-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team14App', '0002_historia_clinica_fecha_historia_clinica_id_medico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pacienteMedicoRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team14App.medicos')),
                ('id_paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team14App.pacientes')),
            ],
        ),
    ]
