# Generated by Django 4.1.1 on 2022-09-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team14App', '0003_pacientemedicorel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientemedicorel',
            name='especialidad',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
