# Generated by Django 4.1.1 on 2022-09-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team14App', '0004_pacientemedicorel_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientemedicorel',
            name='especialidad',
        ),
        migrations.AddConstraint(
            model_name='pacientemedicorel',
            constraint=models.UniqueConstraint(fields=('id_paciente', 'id_medico'), name='unique_migration_host_combination'),
        ),
    ]
