# Generated by Django 4.1.1 on 2022-09-18 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team14App', '0005_remove_pacientemedicorel_especialidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historia_signos',
            old_name='id',
            new_name='id_history',
        ),
    ]
