# Generated by Django 4.1.1 on 2022-09-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team14App', '0006_rename_id_historia_signos_id_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_signos',
            name='fecha',
            field=models.CharField(default='17/09/2022, 22:47:39', max_length=50),
        ),
    ]
