# Generated by Django 4.1.1 on 2022-09-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team14App', '0009_rename_id_history_historia_signos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_clinica',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
    ]
